package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping(path = "/usuario") // This means URL's start with /demo (after Application path)
public class UserController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping(path = "/add") // Map ONLY GET Requests
    public @ResponseBody
    String addNewUser(@RequestParam String name,
            @RequestParam String email) {
        User n = new User();
        n.setName(name);
        n.setEmail(email);
        userRepository.save(n);
        return "Salvado";
    }

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @GetMapping(path = "/delete")
    public @ResponseBody
    String deleteUser(@RequestParam long id) {

        if (!userRepository.exists(id)) {
            return "No hay registro";
        } else {
            User n = userRepository.findOne(id);
            userRepository.delete(n);
            return "Borrado";
        }
    }

    @GetMapping(path = "/update")
    public @ResponseBody
    String updateUser(@RequestParam long id, @RequestParam String name,
            @RequestParam String email) {
        if (!userRepository.exists(id)) {
            return "No hay registro";
        } else {
            User n = userRepository.findOne(id);
            n.setName(name);
            n.setEmail(email);
            userRepository.save(n);
            return "Actualizado";
        }
    }
}
